// src/Kanbas/Courses/Assignments/reducer.ts
import { createSlice, PayloadAction } from "@reduxjs/toolkit";

// Define the structure of an Assignment
export type Assignment = {
  _id: string;
  title: string;
  description: string;
  points: number;
  dueDate: string;
  availableFrom: string;
  availableUntil: string;
  course: string;
};

// Initial state with an empty array of assignments
const initialState = {
  assignments: [] as Assignment[],
};

// Create a slice for the assignments reducer
const assignmentsSlice = createSlice({
  name: "assignments",
  initialState,
  reducers: {
    /**
     * Sets the list of assignments in the state.
     * @param state - The current state.
     * @param action - The payload containing an array of assignments.
     */
    setAssignments: (state, action: PayloadAction<Assignment[]>) => {
      state.assignments = action.payload;
    },

    /**
     * Adds a new assignment to the state.
     * @param state - The current state.
     * @param action - The payload containing the new assignment.
     */
    addAssignment: (state, action: PayloadAction<Assignment>) => {
      state.assignments.push(action.payload);
    },

    /**
     * Updates an existing assignment in the state.
     * @param state - The current state.
     * @param action - The payload containing the updated assignment.
     */
    updateAssignmentAction: (state, action: PayloadAction<Assignment>) => {
      const index = state.assignments.findIndex((a) => a._id === action.payload._id);
      if (index >= 0) {
        state.assignments[index] = action.payload;
      }
    },

    /**
     * Deletes an assignment from the state.
     * @param state - The current state.
     * @param action - The payload containing the ID of the assignment to delete.
     */
    deleteAssignmentAction: (state, action: PayloadAction<string>) => {
      state.assignments = state.assignments.filter((a) => a._id !== action.payload);
    },
  },
});

// Export the actions generated by createSlice
export const {
  setAssignments,
  addAssignment,
  updateAssignmentAction,
  deleteAssignmentAction,
} = assignmentsSlice.actions;

// Export the reducer to use in the Redux store
export default assignmentsSlice.reducer;
